### ISSUE TITLE
ERR_CONNECTION_REFUSED when connecting to websocket

### ISSUE THREAD

**Issue by andrewda** [peace-maker/sm-websocket#3]
I'm using the `websocket_test.sp` code from [here](https://forums.alliedmods.net/showthread.php?t=182615). Everything loads as expected AFAIK from the server, and there are no obvious errors. However, when trying to connect to the websocket with JavaScript, I'm receiving this error: 

```
WebSocket connection to 'ws://192.241.201.125:12345/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

I'm not sure how I can connect. Help would be much appreciated!

**Comment by peace-maker** [comment]
Are you using the latest version of the websocket plugin from this git or the one from the forums? The latest git version is untested.

**Comment by andrewda** [comment]
Tried on both, and am getting the same issue.

**Comment by peace-maker** [comment]
You might had the port blocked?
